image: gradle:6.8.2-jdk8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .gradle
    - ~/.gradle


build:
  stage: build
  script:
  - rm -rf build
  - gradle shadowJar
  artifacts:
    paths:
    - build/libs

pages:
  stage: build
  image: gradle:6.8.3-jdk15
  only:
  - master
  script:
  - gradle javadoc
  - mv build/docs/javadoc public
  artifacts:
    paths:
    - public

test:
  stage: test
  dependencies:
  - build
  script:
  - gradle test

upload to updater:
  stage: deploy
  only:
  - master
  dependencies:
  - build
  script:
  - cd build/libs
  - files=(*)
  - curl -i -F "submit=true" -F "secret=$UPLOAD_SECRET" -F "file=@${files[0]}" https://ajg0702.us/pl/updater/upload.php
