image: maven:3.3.9-jdk-8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


pages:
  script:
  - mvn install
  - mv target/apidocs public
  artifacts:
    paths:
    - public

